---
# tasks file for MongoDB_LinuxOS
  - name: Ensure SELinux Port for MongoDB is set
    seport:
      ports: "{{ item }}"
      proto: tcp
      setype: mongod_port_t
      state: present
    with_items: mongodb_ports
    when: mongodb_selinux_enabled == True

  - name: Disable selinux if config requests
    selinux:
      state: disabled
    when: mongodb_selinux_enabled == False

  - name: Set limits for MongoDB
    pam_limits:
      domain: "{{ item['domain'] }}"
      limit_type: "{{ item['limit_type'] }}"
      limit_item: "{{ item['limit_item'] }}"
      value: "{{ item['value'] }}"
    with_items:
      - { "domain": "root", "limit_type": "soft" , "limit_item": "nofile", "value": 8192 }
      - { "domain": "root", "limit_type": "hard" , "limit_item": "nofile", "value": 8192 }
      - { "domain": "mongod", "limit_type": "soft" , "limit_item": "nofile", "value": 8192 }
      - { "domain": "mongod", "limit_type": "hard" , "limit_item": "nofile", "value": 8192 }

  - name: Set swappiness
    sysctl:
      name: vm.swappiness
      value: "{{ swappiness }}"
      state: present

  - name: Disable transparent hugpages
    debug:
      msg: "No implemented yet"

  - name: Ensure process limits are set
    template:
      src: templates/99-mongodb-nproc.conf.j2
      dest: /etc/security/limits.d/99-mongodb-nproc.conf

  - name: Ensure ntpd is installed
    yum:
      name: ntpd
      state: installed

  - name: Ensure ntpd is started & on
    service:
      name: ntpd
      state: started
      enabled: yes
